Add repos/terraform.tfstate for PR #189
- Someone upgraded this to 0.12 which is a _large_ upgrade and probably
  broke unintended things.
- The only thing this doesn't do for #189 is
  module.repo_verify_release_notes_generator.github_team_repository.repo_team_push
  because of 0.12 weirdness:

  ```
  Error: Unexpected ID format (""), expected numerical ID. strconv.ParseInt: parsing "": invalid syntax
  ```

  I'll look into this tomorrow.